# specify which database and adapter to use for which environment

development:
  adapter: sqlite3
  database: db/mountain-development

test:
  adapter: sqlite3
  database: db/mountain-test

production:
  adapter: sqlite3
  database: db/mountain-production
